### ISSUE TITLE
MultiUploaderField coreRouter image preview router was wrong

### ISSUE THREAD

**Issue by yinminc** [lyrasoft/earth#60]
demo website http://demo.lyrasoft.net/LOST-N/www/ 

<img width="960" alt="截圖 2020-12-01 下午6 43 07" src="https://user-images.githubusercontent.com/28665511/100730540-24b11d00-3405-11eb-950d-ad6a307766df.png">
![截圖 2020-12-01 下午6 44 09](https://user-images.githubusercontent.com/28665511/100730624-3e526480-3405-11eb-8987-61885a60760b.png)

**Comment by asika32764** [comment]
Fixed
