### ISSUE TITLE
[bug] 前台-忘記密碼，不應失敗且有錯誤訊息

### ISSUE THREAD

**Issue by ivylai012** [lyrasoft/earth#92]
從武士農場來的問題，https://github.com/lyrasoft/wushifarm/issues/107

位置：前台-忘記密碼
描述：
在忘記密碼內送出 mail 帳號，不應出現下方訊息

<img width="1345" alt="image" src="https://github.com/lyrasoft/wushifarm/assets/119553033/f511bdbe-76ed-401b-9732-a3c2dacfd276">

**Comment by yinminc** [comment]
@ivylai012 已更新完成，可以再到武士農場正式站測試

**Comment by ivylai012** [comment]
已於武士測試okay
https://github.com/lyrasoft/wushifarm/issues/107#issuecomment-1827196515
