### ISSUE TITLE
[BUG] when i update to php 8.2, there was a bug which show policy not exist.

### ISSUE THREAD

**Issue by yinminc** [lyrasoft/earth#93]
ref 

https://github.com/lyrasoft/ncu-vcrc/issues/181

when i update to php 8.2, there was a bug which show policy not exist.

<img width="1512" alt="330384206-d1675f97-0a9f-4a07-9eed-d74cf8002036" src="https://github.com/lyrasoft/earth/assets/28665511/fe11e4ec-2c3e-4efc-8d7e-b25a0a9164a2">

**Comment by asika32764** [comment]
Fixed https://github.com/windwalker-io/framework/commit/2ac31f0784eac2d4b1d46c99aaceb9b156d5964b
